# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTeste3ViabilidadeTESTE():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_teste3ViabilidadeTESTE(self):
    self.driver.get("http://intranetmeincol/intranet/gpe/inicial.php?projeto=2229")
    self.driver.set_window_size(1567, 423)
    self.driver.find_element(By.ID, "buscar").click()
    self.driver.find_element(By.ID, "buscar").send_keys("2538.1")
    self.driver.find_element(By.ID, "buscar").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "2538.1").click()
    self.driver.find_element(By.LINK_TEXT, "2.3 - Viabilidade Industrial").click()
    self.driver.find_element(By.ID, "largura_tira").click()
    self.driver.find_element(By.ID, "largura_tira").send_keys("590")
    self.driver.find_element(By.CSS_SELECTOR, ".tabela:nth-child(10) tr:nth-child(6)").click()
    self.driver.find_element(By.NAME, "perfuracao").send_keys("0,72")
    self.driver.find_element(By.ID, "salvar").click()
    assert self.driver.find_element(By.ID, "operacao_slitter").is_selected() is False
    assert self.driver.find_element(By.ID, "operacao_perfiladeira").is_selected() is False
    self.driver.find_element(By.ID, "ano_fiscal").click()
    dropdown = self.driver.find_element(By.ID, "ano_fiscal")
    dropdown.find_element(By.XPATH, "//option[. = '2022']").click()
    self.driver.find_element(By.ID, "salvar").click()
  
