# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestePreencherCheckList():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testePreencherCheckList(self):
    self.driver.get("http://intranetmeincol/intranet/gpe/inicial.php?projeto=2268")
    self.driver.set_window_size(1567, 423)
    self.driver.find_element(By.LINK_TEXT, "2.3 - Viabilidade Industrial").click()
    self.driver.find_element(By.NAME, "status1").click()
    self.driver.find_element(By.NAME, "status2").click()
    self.driver.find_element(By.NAME, "status3").click()
    self.driver.find_element(By.NAME, "status4").click()
    self.driver.find_element(By.NAME, "status5").click()
    self.driver.find_element(By.NAME, "status6").click()
    self.driver.find_element(By.NAME, "status7").click()
    self.driver.find_element(By.NAME, "status8").click()
    self.driver.find_element(By.NAME, "status9").click()
    self.driver.find_element(By.NAME, "status10").click()
    self.driver.find_element(By.NAME, "status11").click()
    self.driver.find_element(By.NAME, "status12").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(14) > td:nth-child(5) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(15) > td:nth-child(5) > input").click()
    self.driver.find_element(By.NAME, "status15").click()
    self.driver.find_element(By.NAME, "status16").click()
    self.driver.find_element(By.LINK_TEXT, "2.3 - Viabilidade Industrial").click()
  
