# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTeste1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_teste1(self):
    self.driver.find_element(By.ID, "usuario").click()
    self.driver.find_element(By.ID, "usuario").send_keys("eng_produto6")
    self.driver.find_element(By.ID, "senha").send_keys("vMeincol\\20191")
    self.driver.find_element(By.ID, "senha").send_keys("vMeincol\\20191")
    self.driver.find_element(By.ID, "usuario").send_keys(Keys.ENTER)
    self.driver.get("http://intranetmeincol/intranet/gpe/autorizacao_engenharia.php")
    self.driver.find_element(By.ID, "usuario").click()
    self.driver.find_element(By.ID, "usuario").send_keys("eng_produto6")
    self.driver.find_element(By.ID, "senha").send_keys("vMeincol\\20191")
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    self.driver.find_element(By.ID, "buscar").click()
    self.driver.find_element(By.ID, "buscar").send_keys("2272")
    self.driver.find_element(By.ID, "comboBusca").click()
    dropdown = self.driver.find_element(By.ID, "comboBusca")
    dropdown.find_element(By.XPATH, "//option[. = 'Projeto']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btnBusca > input").click()
    self.driver.find_element(By.LINK_TEXT, "2272.6").click()
  
