# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteUploadPDF():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeUploadPDF(self):
    self.driver.get("http://intranetmeincol/intranet/gpe/inicial.php?projeto=2268")
    self.driver.find_element(By.LINK_TEXT, "2538.1").click()
    self.driver.find_element(By.LINK_TEXT, "Início").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) a > img").click()
    self.driver.find_element(By.LINK_TEXT, "Adicionar Documento").click()
    self.driver.find_element(By.ID, "titulo").click()
    self.driver.find_element(By.ID, "titulo").send_keys("Revisão Técnica")
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(27) > tbody > tr").click()
    self.driver.find_element(By.ID, "titulo").send_keys("Análise Técnica")
    self.driver.find_element(By.ID, "arquivo").click()
    self.driver.find_element(By.ID, "arquivo").send_keys("C:\\fakepath\\PJT 2538.1.pdf")
    self.driver.find_element(By.ID, "salvar").click()
    self.driver.find_element(By.LINK_TEXT, "2.3 - Viabilidade Industrial").click()
  
